#!/usr/bin/env python3
"""Build the static RedrawStates website."""

import argparse
import shutil
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SITE_FILES = (
    "index.html",
    "clippy.svg",
    "css",
    "js",
    "data",
)
BUILD_MARKER = ".redraw-site-build"


def build_site(destination: Path) -> Path:
    """Copy the browser application into a clean deployment directory."""
    destination = destination.expanduser().absolute()

    if destination.is_symlink():
        raise ValueError("The deployment destination cannot be a symlink.")

    if destination == ROOT or destination in ROOT.parents:
        raise ValueError("The deployment destination cannot contain the repository.")

    if ROOT in destination.parents and destination != ROOT / "dist":
        raise ValueError("Inside the repository, only dist/ may be used as the output.")

    if destination.exists():
        if not destination.is_dir():
            raise ValueError("The deployment destination is not a directory.")
        if not (destination / BUILD_MARKER).is_file():
            raise ValueError(
                "Refusing to replace a directory that was not created by this builder."
            )

    destination.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(
        prefix=".redraw-build-",
        dir=destination.parent,
    ) as temporary_directory:
        staged = Path(temporary_directory) / "site"
        staged.mkdir()

        for relative_path in SITE_FILES:
            source = ROOT / relative_path
            target = staged / relative_path

            if not source.exists():
                raise FileNotFoundError(f"Missing website source: {source}")

            if source.is_dir():
                shutil.copytree(source, target)
            else:
                shutil.copy2(source, target)

        (staged / BUILD_MARKER).write_text(
            "Generated by scripts/build-site.py\n",
            encoding="utf-8",
        )

        if destination.exists():
            shutil.rmtree(destination)

        staged.rename(destination)

    return destination


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a deployable static copy of RedrawStates."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "dist",
        help="Output directory (default: repository/dist).",
    )
    args = parser.parse_args()

    try:
        destination = build_site(args.output)
    except (OSError, ValueError) as exc:
        parser.exit(1, f"Build failed: {exc}\n")

    print(f"Static site built: {destination}")
    print("Upload the contents of this directory to the website.")


if __name__ == "__main__":
    main()